-- ==============================================================================
-- Neovim Lua syntax additions for C/C++
-- Language:        C Additions
-- Original Author: Mikhail Wolfson, Jon Haggblad <https://github.com/octol>
-- Maintainer:      bfrg <https://github.com/bfrg>
-- Website:         https://github.com/bfrg/vim-c-cpp-modern
-- Last Change:     Oct 2, 2024
-- Lua Port:        Generated by M365 Copilot (AI) on Dec 24, 2025
-- ==============================================================================
--
-- Notes:
-- - Vim's :syn items do not have a pure Lua API; we use vim.cmd to define them.
-- - Highlight links use vim.api.nvim_set_hl().
-- - Global toggles honored:
--     g.cpp_function_highlight      (default: 1)
--     g.cpp_member_highlight        (default: 0)
--     g.cpp_type_name_highlight     (default: 1)
--     g.cpp_operator_highlight      (default: 0)
--     g.cpp_simple_highlight        (default: 0)
--
-- Installation:
--   require("c").setup()
-- or in after/syntax/c.lua / cpp.lua:
--   require("c").apply(0)

local M = {}

local function get_g(name, default)
	local v = vim.g[name]
	if v == nil then return default end
	return v
end

local function syn_in_buf(bufnr, cmd)
	vim.api.nvim_buf_call(bufnr, function()
		vim.cmd(cmd)
	end)
end

function M.apply(bufnr)
	bufnr = bufnr or 0
	local ft = vim.bo[bufnr].filetype

	syn_in_buf(bufnr, [[syn keyword cTodo contained BUG NOTE]])

	if get_g('cpp_function_highlight', 1) ~= 0 then
		syn_in_buf(bufnr, [[syn match cUserFunction "\<\h\w*\ze\_s\{-}(\%(\*\h\w*)\_s\{-}(\)\@!"]])
		syn_in_buf(bufnr, [[syn match cUserFunctionPointer "\%((\s*\*\s*\)\@6<=\h\w*\ze\s*)\_s\{-}(.*)"]])
		vim.api.nvim_set_hl(0, 'cUserFunction', { link = 'Function' })
		vim.api.nvim_set_hl(0, 'cUserFunctionPointer', { link = 'Function' })
	end

	if get_g('cpp_member_highlight', 0) ~= 0 then
		syn_in_buf(bufnr, [[syn match cMemberAccess "\.\|->" nextgroup=cStructMember,cppTemplateKeyword]])
		syn_in_buf(bufnr, [[syn match cStructMember "\<\h\w*\>\%((\|<)\@!" contained]])
		syn_in_buf(bufnr, [[syn cluster cParenGroup add=cStructMember]])
		syn_in_buf(bufnr, [[syn cluster cPreProcGroup add=cStructMember]])
		syn_in_buf(bufnr, [[syn cluster cMultiGroup add=cStructMember]])
		vim.api.nvim_set_hl(0, 'cStructMember', { link = 'Identifier' })

		if ft == 'cpp' then
			syn_in_buf(bufnr, [[syn keyword cppTemplateKeyword template]])
			vim.api.nvim_set_hl(0, 'cppTemplateKeyword', { link = 'cppStructure' })
		end
	end

	if get_g('cpp_type_name_highlight', 1) ~= 0 then
		syn_in_buf(bufnr, [[syn match cTypeName "\%(\<\%(struct\|union\|enum\)\s\+\)\@8<=\h\w*"]])
		vim.api.nvim_set_hl(0, 'cTypeName', { link = 'Type' })

		if ft == 'cpp' then
			syn_in_buf(bufnr, [[syn match cTypeName "\%(\<\%(class\|using\|concept\|requires\)\s\+\)\@10<=\h\w*"]])
		end
	end

	if get_g('cpp_operator_highlight', 0) ~= 0 then
		syn_in_buf(bufnr, [[syn match cOperator "[?!~*&%<>^|=,+]"]])
		syn_in_buf(bufnr, [[syn match cOperator "[][]"]])
		syn_in_buf(bufnr, [[syn match cOperator "[^:]\@1<=:[^:]\@="]])
		syn_in_buf(bufnr, [[syn match cOperator "-[^>]"me=e-1]])
		syn_in_buf(bufnr, [[syn match cOperator "/[^/*]"me=e-1]])
	end

	syn_in_buf(bufnr,
		[[syn keyword cAnsiName PRId8 PRIi16 PRIo32 PRIu64 PRId16 PRIi32 PRIo64 PRIuLEAST8 PRId32 PRIi64 PRIuLEAST8 PRIuLEAST16 PRId64 PRIiLEAST8 PRIuLEAST16 PRIuLEAST32 PRIdLEAST8 PRIiLEAST16 PRIuLEAST32 PRIuLEAST64 PRIdLEAST16 PRIiLEAST32 PRIuLEAST64 PRIuFAST8 PRIdLEAST32 PRIiLEAST64 PRIoFAST8 PRIuFAST16 PRIdLEAST64 PRIiFAST8 PRIoFAST16 PRIuFAST32 PRIdFAST8 PRIiFAST16 PRIoFAST32 PRIuFAST64 PRIdFAST16 PRIiFAST32 PRIoFAST64 PRIuMAX PRIdFAST32 PRIiFAST64 PRIoMAX PRIuPTR PRIdFAST64 PRIiMAX PRIoPTR PRIx8 PRIdMAX PRIiPTR PRIu8 PRIx16 PRIdPTR PRIo8 PRIu16]])
	syn_in_buf(bufnr,
		[[syn keyword cAnsiName PRIx32 PRIi8 PRIo16 PRIu32 PRIx64 PRIxLEAST8 SCNd8 SCNiFAST32 SCNuLEAST32 PRIxLEAST16 SCNd16 SCNiFAST64 SCNuLEAST64 PRIxLEAST32 SCNd32 SCNiMAX SCNuFAST8 PRIxLEAST64 SCNd64 SCNiPTR SCNuFAST16 PRIxFAST8 SCNdLEAST8 SCNo8 SCNuFAST32 PRIxFAST16 SCNdLEAST16 SCNo16 SCNuFAST64 PRIxFAST32 SCNdLEAST32 SCNo32 SCNuMAX PRIxFAST64 SCNdLEAST64 SCNo64 SCNuPTR PRIxMAX SCNdFAST8 SCNoLEAST8 SCNx8 PRIxPTR SCNdFAST16 SCNoLEAST16 SCNx16]])
	syn_in_buf(bufnr,
		[[syn keyword cAnsiName PRIX8 SCNdFAST32 SCNoLEAST32 SCNx32 PRIX16 SCNdFAST64 SCNoLEAST64 SCNx64 PRIX32 SCNdMAX SCNoFAST8 SCNxLEAST8 PRIX64 SCNdPTR SCNoFAST16 SCNxLEAST16 PRIXLEAST8 SCNi8 SCNoFAST32 SCNxLEAST32 PRIXLEAST16 SCNi16 SCNoFAST64 SCNxLEAST64 PRIXLEAST32 SCNi32 SCNoMAX SCNxFAST8 PRIXLEAST64 SCNi64 SCNoPTR SCNxFAST16 PRIXFAST8 SCNiLEAST8 SCNu8 SCNxFAST32 PRIXFAST16 SCNiLEAST16 SCNu16 SCNxFAST64 PRIXFAST32 SCNiLEAST32 SCNu32 SCNxMAX PRIXFAST64 SCNiLEAST64 SCNu64 SCNxPTR PRIXMAX SCNiFAST8 SCNuLEAST8 PRIXPTR SCNiFAST16 SCNuLEAST16]])
	syn_in_buf(bufnr, [[syn keyword cAnsiName STDC CX_LIMITED_RANGE STDC FENV_ACCESS STDC FP_CONTRACT]])
	syn_in_buf(bufnr,
		[[syn keyword cAnsiName errno environ and bitor not_eq xor and_eq compl or xor_eq bitand not or_eq]])

	syn_in_buf(bufnr, [[syn keyword cBoolean true false TRUE FALSE]])

	vim.api.nvim_set_hl(0, 'cBoolean', { link = 'Boolean' })
	vim.api.nvim_set_hl(0, 'cAnsiName', { link = 'Identifier' })

	if get_g('cpp_simple_highlight', 0) ~= 0 then
		vim.api.nvim_set_hl(0, 'cStorageClass', { link = 'Statement' })
		vim.api.nvim_set_hl(0, 'cStructure', { link = 'Statement' })
		vim.api.nvim_set_hl(0, 'cTypedef', { link = 'Statement' })
		vim.api.nvim_set_hl(0, 'cLabel', { link = 'Statement' })
	end
end

function M.setup()
	local group = vim.api.nvim_create_augroup('C_Lua_Syntax', { clear = true })
	vim.api.nvim_create_autocmd('FileType', {
		group = group,
		pattern = { 'c', 'cpp' },
		callback = function(args)
			M.apply(args.buf)
		end,
	})
end

return M
